from datetime import datetime

SEED_ARCHITECTURES = [
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/serverless-web-app/",
        "title": "Serverless Web Application",
        "description": "API Gateway, Lambda, DynamoDB. Good for low-traffic web apps.",
        "resources": [
            {"resource_type": "API Gateway", "resource_name": "REST API", "count": 1},
            {"resource_type": "Lambda", "resource_name": "API handlers", "count": 3},
            {"resource_type": "DynamoDB", "resource_name": "Data store", "count": 1},
        ],
        "metadata": {
            "use_case": "web_application",
            "scale": "small",
            "traffic_pattern": "steady",
            "latency_sensitivity": "medium",
            "processing_style": "request_response",
            "data_intensity": "low",
            "availability_requirement": "standard",
            "ops_preference": "managed_services",
            "budget_sensitivity": "high",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/ecommerce-reference/",
        "title": "E-commerce Platform",
        "description": "Multi-tier with ALB, ECS, RDS. Handles bursty traffic.",
        "resources": [
            {"resource_type": "ALB", "resource_name": "Load balancer", "count": 1},
            {"resource_type": "ECS", "resource_name": "App containers", "count": 1},
            {"resource_type": "RDS", "resource_name": "PostgreSQL", "count": 1},
            {"resource_type": "ElastiCache", "resource_name": "Redis cache", "count": 1},
            {"resource_type": "S3", "resource_name": "Static assets", "count": 1},
        ],
        "metadata": {
            "use_case": "ecommerce",
            "scale": "medium",
            "traffic_pattern": "bursty",
            "latency_sensitivity": "medium",
            "processing_style": "request_response",
            "data_intensity": "medium",
            "availability_requirement": "high",
            "ops_preference": "managed_services",
            "budget_sensitivity": "medium",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/real-time-analytics/",
        "title": "Real-Time Analytics Pipeline",
        "description": "Kinesis, Lambda, DynamoDB. Event-driven streaming.",
        "resources": [
            {"resource_type": "Kinesis", "resource_name": "Data streams", "count": 2},
            {"resource_type": "Lambda", "resource_name": "Stream processors", "count": 4},
            {"resource_type": "DynamoDB", "resource_name": "Aggregations", "count": 1},
            {"resource_type": "CloudWatch", "resource_name": "Metrics", "count": 1},
        ],
        "metadata": {
            "use_case": "real_time_analytics",
            "scale": "large",
            "traffic_pattern": "unpredictable",
            "latency_sensitivity": "high",
            "processing_style": "streaming",
            "data_intensity": "high",
            "availability_requirement": "high",
            "ops_preference": "managed_services",
            "budget_sensitivity": "low",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/batch-processing/",
        "title": "Batch Processing with EMR",
        "description": "S3, EMR, Glue. Scheduled large-scale data jobs.",
        "resources": [
            {"resource_type": "S3", "resource_name": "Input/output", "count": 2},
            {"resource_type": "EMR", "resource_name": "Spark cluster", "count": 1},
            {"resource_type": "Glue", "resource_name": "Crawler", "count": 1},
        ],
        "metadata": {
            "use_case": "batch_processing",
            "scale": "large",
            "traffic_pattern": "scheduled",
            "latency_sensitivity": "low",
            "processing_style": "batch",
            "data_intensity": "high",
            "availability_requirement": "standard",
            "ops_preference": "balanced",
            "budget_sensitivity": "medium",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/public-api/",
        "title": "Public API with API Gateway",
        "description": "API Gateway, Lambda, DynamoDB. High availability API.",
        "resources": [
            {"resource_type": "API Gateway", "resource_name": "HTTP API", "count": 1},
            {"resource_type": "Lambda", "resource_name": "Handlers", "count": 5},
            {"resource_type": "DynamoDB", "resource_name": "Backend", "count": 1},
            {"resource_type": "WAF", "resource_name": "Security", "count": 1},
        ],
        "metadata": {
            "use_case": "public_api",
            "scale": "medium",
            "traffic_pattern": "bursty",
            "latency_sensitivity": "high",
            "processing_style": "request_response",
            "data_intensity": "low",
            "availability_requirement": "critical",
            "ops_preference": "managed_services",
            "budget_sensitivity": "medium",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/event-driven/",
        "title": "Event-Driven Architecture",
        "description": "EventBridge, SQS, Lambda. Decoupled processing.",
        "resources": [
            {"resource_type": "EventBridge", "resource_name": "Event bus", "count": 1},
            {"resource_type": "SQS", "resource_name": "Queues", "count": 3},
            {"resource_type": "Lambda", "resource_name": "Consumers", "count": 4},
        ],
        "metadata": {
            "use_case": "event_processing",
            "scale": "medium",
            "traffic_pattern": "spiky",
            "latency_sensitivity": "medium",
            "processing_style": "event_driven",
            "data_intensity": "medium",
            "availability_requirement": "high",
            "ops_preference": "managed_services",
            "budget_sensitivity": "medium",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/media-delivery/",
        "title": "Media Delivery with CloudFront",
        "description": "CloudFront, S3, MediaConvert. CDN for video and images.",
        "resources": [
            {"resource_type": "CloudFront", "resource_name": "CDN", "count": 1},
            {"resource_type": "S3", "resource_name": "Origin", "count": 1},
            {"resource_type": "MediaConvert", "resource_name": "Transcoding", "count": 1},
        ],
        "metadata": {
            "use_case": "media_delivery",
            "scale": "large",
            "traffic_pattern": "bursty",
            "latency_sensitivity": "high",
            "processing_style": "request_response",
            "data_intensity": "high",
            "availability_requirement": "high",
            "ops_preference": "managed_services",
            "budget_sensitivity": "low",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/internal-tool/",
        "title": "Internal Admin Tool",
        "description": "Simple EC2 or Lambda. Low cost, standard availability.",
        "resources": [
            {"resource_type": "EC2", "resource_name": "App server", "count": 1},
            {"resource_type": "RDS", "resource_name": "MySQL", "count": 1},
        ],
        "metadata": {
            "use_case": "internal_tool",
            "scale": "small",
            "traffic_pattern": "steady",
            "latency_sensitivity": "low",
            "processing_style": "request_response",
            "data_intensity": "low",
            "availability_requirement": "standard",
            "ops_preference": "self_managed_ok",
            "budget_sensitivity": "high",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/iot-ingestion/",
        "title": "IoT Data Ingestion",
        "description": "IoT Core, Kinesis, Lambda. Device telemetry at scale.",
        "resources": [
            {"resource_type": "IoT Core", "resource_name": "Device gateway", "count": 1},
            {"resource_type": "Kinesis", "resource_name": "Streams", "count": 2},
            {"resource_type": "Lambda", "resource_name": "Processors", "count": 3},
            {"resource_type": "Timestream", "resource_name": "Time series DB", "count": 1},
        ],
        "metadata": {
            "use_case": "iot_ingestion",
            "scale": "large",
            "traffic_pattern": "unpredictable",
            "latency_sensitivity": "medium",
            "processing_style": "streaming",
            "data_intensity": "high",
            "availability_requirement": "high",
            "ops_preference": "managed_services",
            "budget_sensitivity": "medium",
        },
    },
    {
        "source_url": "https://aws.amazon.com/blogs/architecture/ml-inference/",
        "title": "ML Inference at Scale",
        "description": "SageMaker, Lambda, API Gateway. Model serving.",
        "resources": [
            {"resource_type": "SageMaker", "resource_name": "Endpoint", "count": 1},
            {"resource_type": "API Gateway", "resource_name": "API", "count": 1},
            {"resource_type": "Lambda", "resource_name": "Pre/post processing", "count": 2},
            {"resource_type": "S3", "resource_name": "Model artifacts", "count": 1},
        ],
        "metadata": {
            "use_case": "ml_inference",
            "scale": "medium",
            "traffic_pattern": "bursty",
            "latency_sensitivity": "high",
            "processing_style": "request_response",
            "data_intensity": "medium",
            "availability_requirement": "high",
            "ops_preference": "managed_services",
            "budget_sensitivity": "low",
        },
    },
]


def get_seed_docs():
    now = datetime.utcnow()
    docs = []
    for i, arch in enumerate(SEED_ARCHITECTURES):
        doc = {
            "source_url": arch["source_url"],
            "title": arch["title"],
            "description": arch["description"],
            "raw_content": arch["description"],
            "scraped_at": now,
            "resources": arch["resources"],
            "metadata": arch["metadata"],
        }
        docs.append(doc)
    return docs
